### ISSUE TITLE
Docs: convert .doc file to Markdown

### ISSUE THREAD

**Issue by perlun** [Microsoft/ILMerge#13]
Hi,

Have been using ILMerge for years, thanks for an excellent tool. Didn't know until now that it has been open sourced, great work @mike-barnett and the other people at Microsoft. 😄 

I have a small suggestion: the documentation is currently available as a [Word file](https://github.com/Microsoft/ILMerge/blob/master/ILMerge.doc). This makes it a little bit more awkward to consume. Markdown has taken over the world since this project was created, and converting this document to Markdown would make it a lot more accessible via the web browser etc.

This issue exists to discuss the matter. Would you accept a PR that converts the documentation to Markdown, or would you like to fix it yourself, or do you consider it a stupid idea or...? 😉

**Comment by mike-barnett** [comment]
Thanks and that would be a fantastic idea! A PR would be greatly appreciated! If it is a Markdown file, then it will even show up on this site as a web page, like any .md file, right? And now would be a great time to do it: I'm (finally) putting together a new NuGet package to publish.

**Comment by perlun** [comment]
> Thanks and that would be a fantastic idea! A PR would be greatly appreciated!

There we go, #14 has been created for your pleasure. 😄 

> If it is a Markdown file, then it will even show up on this site as a web page, like any .md file, right?

Right. I also added a link to it from the front page (README.md).

> And now would be a great time to do it: I'm (finally) putting together a new NuGet package to publish.

Even better. 😄 I just happened to find myself here because I was tweaking some ILMerge settings in a legacy project of ours, and wanted to check up the command line syntax etc.

**Comment by mike-barnett** [comment]
Thanks! This is wonderful!
