### ISSUE TITLE
new nuget release?

### ISSUE THREAD

**Issue by javagg** [Microsoft/ILMerge#18]
The latest version of ilmerge on nuget.org is 2.14.1208. When will the 2.15 come out?

**Comment by AustinWise** [comment]
To add to this, the README's example has a `PackageReference` to version 2.15.0, but the linked Nuget page only has version 2.14.1208. Is there somewhere else a newer version of this package is published?

**Comment by bqstony** [comment]
@mike-barnett please push the latest release to nuget.org for easy integration into csproj. A Alpha version would be also nice.

The generated nuget from source has work for me.

**Comment by mike-barnett** [comment]
Yes, sorry about that. I have run into roadblocks in getting through the process for getting an "official" release from inside the company and I can't do it without that. For now I'm afraid the best thing is to build it yourself from source.

**Comment by mike-barnett** [comment]
I believe the build/release process is now working and new versions are available on NuGet.
