### ISSUE TITLE
C# exception filters are corrupted

### ISSUE THREAD

**Issue by sunahe** [Microsoft/ILMerge#19]
Try to run ILMerge on a project that contains C# exception filters:
https://github.com/sunahe/TestExceptionFilters

Run the processed file.

Result:
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at TestExceptionFilters.Program.Main(String[] args)

**Comment by mike-barnett** [comment]
Thanks for the great repo! That made it super easy to track down and fix. Fixed by commit 0528aaa.
