### ISSUE TITLE
setup authenticode signing for ilmerge in vsts

### ISSUE THREAD

**Issue by rohit21agrawal** [Microsoft/ILMerge#33]
Steps to be done:

ilmerge ilmerge.exe and system.compiler.dll as a post build step
get ilmerge.exe signed in the vsts ci.

**Comment by bencyoung** [comment]
This would be very useful for us as currently ILMerge is blocked by our security software from running on our CI machines which makes it very hard to use. Signing it with an MS key would make it usable for us...

**Comment by bencyoung** [comment]
Is there an ETA on this?

**Comment by jhromadik** [comment]
The latest version, 3.0.29, released 2019-04-10, is signed and time stamped.

**Comment by mike-barnett** [comment]
Looks like this has been taken care of. Thanks all!
