### ISSUE TITLE
Error message allowDup parameter misspelled

### ISSUE THREAD

**Issue by nnpcYvIVl** [Microsoft/ILMerge#39]
Can you fix the following error message to say allowDup instead of alllowDup?

ILMerge.Merge: ERROR!!: Duplicate type 'Microsoft.VisualStudio.Setup.Configuration.IEnumSetupInstances' found in assembly 'Microsoft.Build.Tasks.Core'. Do you want to use the **/alllowDup** option?

**Comment by jnm2** [comment]
This is already fixed in https://github.com/Microsoft/ILMerge/pull/20.

**Comment by jnm2** [comment]
@mike-barnett Would this have shipped on NuGet yet?
