### ISSUE TITLE
IlMerge.exe process does not exit 

### ISSUE THREAD

**Issue by Gambero81** [Microsoft/ILMerge#48]
I'm trying to merge 2 .net framework 4.5.2 dll, with:

`ILMerge.exe /lib:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2" /ndebug /log:"C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.Merged.log" /target:library /out:"C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.Merged.dll" "C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.dll" "C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Utils.dll"`

using ILMerge.exe.config:
`<configuration>
    <startup useLegacyV2RuntimeActivationPolicy="true">
        <requiredRuntime safemode="true" imageVersion="v4.0.30319" version="v4.0.30319"/>
    </startup>
</configuration>`

the ilmerge.exe process remain running indefinitely without return...

Here is the log:

ILMerge version 2.12.803.0
Copyright (C) Microsoft Corporation 2004-2006. All rights reserved.
ILMerge /lib:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2 /ndebug /log:C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.Merged.log /target:library /out:C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.Merged.dll C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.dll C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Utils.dll 
Set platform to 'v2', using directory 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\..\v2.0.50727' for mscorlib.dll
Running on Microsoft (R) .NET Framework v4.0.30319
mscorlib.dll version = 4.0.0.0
The list of input assemblies is:
	C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.dll
	C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Utils.dll
Trying to read assembly from the file 'C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.dll'.
	Successfully read in assembly.
	There were no errors reported in DPGDocumentsHub.Api's metadata.
Trying to read assembly from the file 'C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Utils.dll'.
	Successfully read in assembly.
	There were no errors reported in DPGDocumentsHub.Utils's metadata.
Checking to see that all of the input assemblies have a compatible PeKind.
	DPGDocumentsHub.Api.PeKind = ILonly
	DPGDocumentsHub.Utils.PeKind = ILonly
All input assemblies have a compatible PeKind value.
AssemblyResolver: Assembly 'DPGDocumentsHub.Api' is referencing assembly 'RestSharp'.
	AssemblyResolver: Attempting referencing assembly's directory.
Resolved assembly reference 'RestSharp' to 'C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\RestSharp.dll'. (Used referencing Module's directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'System.Drawing'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Drawing' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Drawing.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'System.Data'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Data' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'System.Data' is referencing assembly 'System'.
	AssemblyResolver: Attempting referencing assembly's directory.
Resolved assembly reference 'System' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll'. (Used referencing Module's directory.)
AssemblyResolver: Assembly 'System.Data' is referencing assembly 'System.Xml'.
	AssemblyResolver: Attempting referencing assembly's directory.
Resolved assembly reference 'System.Xml' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.dll'. (Used referencing Module's directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Api' is referencing assembly 'System.Core'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Core' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Api' is referencing assembly 'Newtonsoft.Json'.
	AssemblyResolver: Attempting referencing assembly's directory.
Resolved assembly reference 'Newtonsoft.Json' to 'C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\Newtonsoft.Json.dll'. (Used referencing Module's directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'System.Web'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Web' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Web.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'Kendo.Mvc'.
	AssemblyResolver: Attempting referencing assembly's directory.
Resolved assembly reference 'Kendo.Mvc' to 'C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\Kendo.Mvc.dll'. (Used referencing Module's directory.)
Using assembly 'DPGDocumentsHub.Api' for assembly-level attributes for the target assembly.
Merging assembly 'DPGDocumentsHub.Api' into target assembly.
Merging assembly 'DPGDocumentsHub.Utils' into target assembly.
Duplicate type name: modifying name of the type '' (from assembly 'DPGDocumentsHub.Utils') to 'DPGDocumentsHub.Utils23664.'
Duplicate type name: modifying name of the type '' (from assembly 'DPGDocumentsHub.Utils') to 'DPGDocumentsHub.Utils23664.'
Duplicate type name: modifying name of the type '' (from assembly 'DPGDocumentsHub.Utils') to 'DPGDocumentsHub.Utils23664.'
Duplicate type name: modifying name of the type '' (from assembly 'DPGDocumentsHub.Utils') to 'DPGDocumentsHub.Utils23664.'
Copying 1 Win32 Resources from assembly 'DPGDocumentsHub.Api' into target assembly.
	There were no errors reported in the target assembly's metadata.
ILMerge: Writing target assembly 'C:\DPGDocumentsHub\DPGDocumentsHub.Web\bin\DPGDocumentsHub.Api.Merged.dll'.
AssemblyResolver: Assembly 'DPGDocumentsHub.Api' is referencing assembly 'Microsoft.CSharp'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'Microsoft.CSharp' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Api' is referencing assembly 'System.Web.Extensions'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Web.Extensions' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Web.Extensions.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'Newtonsoft.Json' is referencing assembly 'System.Numerics'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Numerics' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Numerics.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'Newtonsoft.Json' is referencing assembly 'System.Xml.Linq'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Xml.Linq' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'System.Configuration'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Configuration' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Configuration.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'System.Data.DataSetExtensions'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Data.DataSetExtensions' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.DataSetExtensions.dll'. (Used a client-supplied directory.)
AssemblyResolver: Assembly 'DPGDocumentsHub.Utils' is referencing assembly 'System.Management'.
	AssemblyResolver: Attempting referencing assembly's directory.
	AssemblyResolver: Did not find assembly in referencing assembly's directory.
	AssemblyResolver: Attempting input directory.
	AssemblyResolver: Did not find assembly in input directory.
	AssemblyResolver: Attempting user-supplied directories.
Resolved assembly reference 'System.Management' to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Management.dll'. (Used a client-supplied directory.)

**Comment by mike-barnett** [comment]
I'm not sure why you would need the config file. Also, can you please add the targetplatform option? I think that might be the problem. Let me know if that helps.

**Comment by Gambero81** [comment]
i used config file to solve error "Unresolved assembly reference not allowed: System.Core" as suggested in https://stevemichelotti.com/ilmerge-unresolved-assembly-reference-not-allowed-system/

removing config file and adding targetplatform option as you suggested work fine!

Thanks

**Comment by mike-barnett** [comment]
Yay! I'm glad that worked for you.
