### ISSUE TITLE
Remove dependency on .NET 3.5

### ISSUE THREAD

**Issue by thomaslevesque** [Microsoft/ILMerge#56]
Currently [ILMerge depends on .NET 3.5](https://stackoverflow.com/a/37343880/98713). I don't know how/why (the executable targets .NET 4.5.2), but the fact is it doesn't work without it.

This should be fixed; .NET 3.5 is 10 years old and completely obsolete. In the meantime, it should at least be documented somewhere.

**Comment by mike-barnett** [comment]
Hmm, I just checked and every project in the solution targets 4.5.2. Do you know how the dependency on 3.5 is created? I'd be happy to remove it. Or are you talking about the ILMerge exe that is available through NuGet.org or the exe that is built from source? I'm moving (slowly...) towards getting a new build and publish process in place so I can update the NuGet version.

**Comment by thomaslevesque** [comment]
I don't think it's an explicit dependency. It crashes when trying to load mscorsn.dll, not sure why.

> Or are you talking about the ILMerge exe that is available through NuGet.org or the exe that is built from source?

From NuGet.org. But your question makes me realize that the problem might already be fixed. There hasn't been a new release in so long that the current code probably has very little to do with the DLL on NuGet...

> I'm moving (slowly...) towards getting a new build and publish process in place so I can update the NuGet version.

In the meantime, would you consider publishing a new release manually?

**Comment by jnm2** [comment]
@thomaslevesque 

> It crashes when trying to load mscorsn.dll, not sure why.

This is fixed in https://github.com/dotnet/ILMerge/pull/3.

**Comment by thomaslevesque** [comment]
> This is fixed in #3.

Thanks, but this fix has never been released. I know I could build ILMerge from source, but I'd really rather avoid it.

**Comment by jnm2** [comment]
Absolutely, just wanted to link the explanation and context about mscorsn.dll in case you were curious.

**Comment by thomaslevesque** [comment]
@mike-barnett I see that new versions have been released on NuGet (thanks!). Is the fix for this included in the new versions?
BTW, I can't find any kind of release notes or change log... Is it documented anywhere?

**Comment by mike-barnett** [comment]
Oh, that definitely is in the NuGet release. I will mercilessly flog our QA team (i.e., myself) but I doubt that will change things about getting better documentation... Sorry!

**Comment by jnm2** [comment]
The place I look for details about what's in a NuGet release is usually https://github.com/dotnet/ILMerge/releases. Failing that, https://github.com/dotnet/ILMerge/blob/master/CHANGELOG.md.

**Comment by thomaslevesque** [comment]
OK, closing this issue then. Thanks!
