### ISSUE TITLE
No way to remove un-referenced code

### ISSUE THREAD

**Issue by i00** [Microsoft/ILMerge#61]
It would be good if you could have ILMerge automatically remove all non-referenced code from non-primary assemblies (excluding ones specified with ExcludeFile)...
If I am merging in a 3rd party library with /Internalize (for example) why would I want all of the components in that library that I am not using?

**Comment by mike-barnett** [comment]
Yeah, that kind of "tree shaking" has been a constant request over the years. It is very difficult because unless you have an entire application you don't know which of the public entry points may get called. In addition, it can be hard to know whether a particular method will actually be called at runtime or not, given both dynamic dispatch and especially the use of reflection. So this is definitely a feature that, as nice as it would be to have, will not be implemented. Sorry!

**Comment by i00** [comment]
You state that "unless you have an entire application you don't know which of the public entry points may get called"...
I said when using /Internalize .... this means that you don't need to know ... Just strip out everything not used that is "internalized" as it will not be accessible anyway (outside of the primary assembly, excluding ones that are exposed through /ExcludeFile).

Kris

**Comment by mike-barnett** [comment]
I get that, but the difficulty is in knowing what is "not used". It is much more difficult than it seems. People often use reflection to find things in a way that can defeat any technique you might use to decide that something is not being accessed.

**Comment by hrumhurum** [comment]
Can confirm that dead code removal is not a trivial task. And it's not only the code, data removal should be considered too as part of "tree shaking" process. Unused embedded resources etc.

Reflection is the main culprit. It makes tree shaking hard.

To give you an example, imagine a WPF XAML page that references a property in a binding path. The binding path is a nested text string with a specific syntax. Unless a tree shaker can read and resolve XAML binding paths during compile time, it will dump the referenced property. As a result, the app won't be able to load that XAML page anymore after dead code removal.

**Comment by mike-barnett** [comment]
Yes, and actually that is why ILMerge doesn't usually work for WPF assemblies: those strings encode the original assembly identity and ILMerge is unable to update those strings to use the new (merged) assembly identity instead.

**Comment by i00** [comment]
> People often use reflection to find things in a way that can defeat any technique you might use to decide that something is not being accessed

If this is required people should use the System.Reflection.Obfuscation attribute - and these should NOT be removed.
Also can't talk for WPF but I have never used the built in binding methods (as I really like type safety and think they are rubbish)...

Have my own extension methods like:
`dtpOnlineClaimingStartDate.AddBindingStrict(x => x.Value, BoundItem, x => x.OnlineClaimingStartDate);`
It has several advantages such as:
- prompting for the properties on the item that you are actually binding
- ensuring that you are binding to the same data type (there is an .AddBinding method also for binding different types)
- Supports plugins that allow other things to happen ... eg if binding an EF entities string property to a .Text property of a text box you could make it automatically set the .MaxLength to the field length

Anyway I think this should be an option - if it doesn't work for something don't use it or have a command switch to allow force inclusion of classes / methods

**Comment by mike-barnett** [comment]
Those are good points. I don't have time to work on this, but if you want to I would be happy to advise. However, I would suggest that it be done in [ilrepack](https://github.com/gluck/il-repack) instead of ILMerge. That really is the right place to advance for static linking. Thanks so much for your interest!
