### ISSUE TITLE
Install-Package : Package 'ilmerge 3.0.21' is not found

### ISSUE THREAD

**Issue by gojimmypi** [Microsoft/ILMerge#62]
I installed Visual Studio 2019 today, and tried to add the `ILMerge` tool using `Install-Package ilmerge -Version 3.0.21` and received a `Install-Package : Package 'ilmerge 3.0.21' is not found` error.

![image](https://user-images.githubusercontent.com/13059545/55505018-0202ab80-5607-11e9-80aa-7231ab88b9ea.png)

Here's the full log of install attempt:
```
Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 5.0.0.5917

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package ilmerge -Version 3.0.21


Attempting to gather dependency information for package 'ilmerge.3.0.21' with respect to project 'myprojectname', targeting '.NETFramework,Version=v4.6.2'
Install-Package : Package 'ilmerge 3.0.21' is not found in the following primary source(s): 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please 
verify all your online package sources are available (OR) package id, version are specified correctly.
At line:1 char:1
+ Install-Package ilmerge -Version 3.0.21
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.0570615
PM> 
```

There's this year-old open issue for NuGet: https://github.com/NuGet/Home/issues/1827 I cleared the cache as suggested, but no luck.

![image](https://user-images.githubusercontent.com/13059545/55505183-6887c980-5607-11e9-80cd-74395a1affde.png)

Does ILMerge work with Visual Studio 2019, or are there other ideas on how to make a single, stand-alone, portable `exe` file without needing all the other DLL's in the same directory?

**Comment by lextm** [comment]
```
Package 'ilmerge 3.0.21' is not found in the following primary source(s): 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please 
verify all your online package sources are available (OR) package id, version are specified correctly.
```
Please re-read the error message, not the irrelevant GitHub thread.

You don't have a valid NuGet feed (like NuGet.org) for VS to locate ILMerge, and that's why it fails.

**Comment by gojimmypi** [comment]
Thank you. I did read the error message.

If I right-click on references, and select `Manage NuGet Packages...` it has this setting:

![image](https://user-images.githubusercontent.com/13059545/55820837-f0ab1a80-5ab0-11e9-90e2-98a5db61ce4f.png)

Is there someplace else that I need to tell Visual Studio to set the NuGet feed?

**Comment by lextm** [comment]
That goes far beyond the scope of ILMerge. But to get rid of VS's illusion, you can run the NuGet command line tool at the root of that project to see the effective feed list (based on messy NuGet configuration system),
```
nuget sources list
```

**Comment by gojimmypi** [comment]
At the package manager prompt? I get an error:

```
PM> nuget sources list
nuget : The term 'nuget' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ nuget sources list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (nuget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM> 
```
I also tried just `sources list`
```
PM> sources list
sources : The term 'sources' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if 
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sources list
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sources:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM> 
```

**Comment by gojimmypi** [comment]
Ugh. There actually _is_ a second place to set the package source. :/

In addition to the documented "right-click on references" mentioned above, there's another setting in the package manager console itself that I didn't notice. Apparently the default is the offline storage, regardless of settings in NuGet Package Manager.

![image](https://user-images.githubusercontent.com/13059545/55830049-ff9bc800-5ac4-11e9-95ea-3a6c29a8dd09.png)

And like most things, obvious when you know the answer, lol.

**Comment by gojimmypi** [comment]
I added some installation instructions to help others avoid this problem of two places to set the package source:

https://github.com/dotnet/ILMerge#installation

While I was there, also added some instructions for a batch file that does not use `msbuild`:

https://github.com/dotnet/ILMerge#to-run-ilmerge-in-a-batch-file
