### ISSUE TITLE
Windows 10 - install ilmerge.3.0.21.nupkg fails

### ISSUE THREAD

**Issue by phillip-from-oz** [Microsoft/ILMerge#63]
Hi,
I'm trying to install ilmerge.3.0.21.nupkg.

I want the ilmerge.exe.

It fails with:
_C:\temp>nuget install ilmerge.3.0.21.nupkg
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'ilmerge.3.0.21.nupkg' to 'C:\temp\AWS-CFN-Build\Release'.
  GET https://api.nuget.org/v3/registration3-gz-semver2/ilmerge.3.0.21.nupkg/index.json
  NotFound https://api.nuget.org/v3/registration3-gz-semver2/ilmerge.3.0.21.nupkg/index.json 907ms
Unable to find package 'ilmerge.3.0.21.nupkg'_

Can some please tell me how to fix this?

I'm using Windows 10.
I got ilmerge from:
https://www.nuget.org/packages/ilmerge

**Comment by lextm** [comment]
Can you run `nuget update -self` first?

**Comment by phillip-from-oz** [comment]
Thanks.
Unfortunately it still doe not work.

C:\temp>nuget.exe update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.9.4.
NuGet.exe is up to date.

C:\temp>nuget install ilmerge.3.0.21.nupkg
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'ilmerge.3.0.21.nupkg' to 'C:\temp'.
  GET https://api.nuget.org/v3/registration3-gz-semver2/ilmerge.3.0.21.nupkg/index.json
  NotFound https://api.nuget.org/v3/registration3-gz-semver2/ilmerge.3.0.21.nupkg/index.json 862ms
Unable to find package 'ilmerge.3.0.21.nupkg'

Any ideas?

**Comment by lextm** [comment]
Please run `nuget install ilmerge`.

**Comment by phillip-from-oz** [comment]
Thanks! That did the trick!

**Comment by phillip-from-oz** [comment]
Thanks.
That worked!
    On Saturday, 6 April 2019, 4:30:50 am AEDT, Lex Li <notifications@github.com> wrote:  
 
 
Please run nuget install ilmerge.
