### ISSUE TITLE
"Private" ILMerge

### ISSUE THREAD

**Issue by TonyValenti** [Microsoft/ILMerge#81]
I want to merge a dependency into my main assembly yet have all of the public but merged-in types be private so that they are not exposed to consumers of my assembly.

How do I make that happen?

**Comment by mike-barnett** [comment]
Check out section 2.12 in [the manual](https://github.com/dotnet/ILMerge/blob/master/ilmerge-manual.md): https://github.com/dotnet/ILMerge/blob/master/ilmerge-manual.md. Let me know if you need any further help.

**Comment by TonyValenti** [comment]
Man!  I even looked at the docs and somehow missed that!  Thanks so much!
